-- создаем PRODUCT Business VPN: порт - COVERAGE_ID = 100 (domestic), SPEED = 2048, TARIFFICATION_SCHEME_ID=100(FIX), TYPE_ID=100 (platinum)
-- сначала порт
INSERT INTO PORT(COVERAGE_ID,SPEED,TARIFFICATION_SCHEME_ID,TYPE_ID) values(100,2048,100,100);

-- создаем PRODUCT: конкретная услуга Business VPN
INSERT INTO BUSINESS_VPN(ID,PORT_ID,SITE_ID,TOWN) SELECT PRODUCT_SEQ.nextval, PORT_SEQ.currval,97,'Пенза' from dual;
-- создаем PRODUCT_ITEM: заполняем обертку для услуги TYPE_ID=100(new) и сразу связываем PRODUCT_ITEM и услугу
INSERT INTO PRODUCT_ITEM(TYPE_ID,PRODUCT_ID,NOTE) SELECT 100, PRODUCT_SEQ.currval, 'Business VPN 2 - test product item' FROM DUAL;

-- связываем сценарий и product item.
insert into SCENARIO_PRODUCTS (PRODUCT_ITEM_ID, SCENARIO_ID) SELECT PRODUCT_ITEM_SEQ.currval, SCENARIO_SEQ.currval FROM DUAL;
-- накидаем параметров услуги Business VPN в ITEM.
-- заполним несколько строковых параметров и прицепим их к product_item
insert into WRAPPER_STRING(VALUE, IDENTIFICATION_ID) values('Новосибирск',2);
insert into WRAPPER_STRING_PARENT(PARENT_ID, WRAPPER_STRING_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_STRING_SEQ.currval FROM DUAL;
insert into WRAPPER_STRING(VALUE, IDENTIFICATION_ID) values('domestic',3);
insert into WRAPPER_STRING_PARENT(PARENT_ID, WRAPPER_STRING_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_STRING_SEQ.currval FROM DUAL;
insert into WRAPPER_STRING(VALUE, IDENTIFICATION_ID) values('upgrade',172);
insert into WRAPPER_STRING_PARENT(PARENT_ID, WRAPPER_STRING_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_STRING_SEQ.currval FROM DUAL;
insert into WRAPPER_STRING(VALUE, IDENTIFICATION_ID) values('upgrade',4);
insert into WRAPPER_STRING_PARENT(PARENT_ID, WRAPPER_STRING_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_STRING_SEQ.currval FROM DUAL;
-- заполним несколько числовых параметров и прицепим их к product_item
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(0.39,21);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(1.25,23);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(0.55,26);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(4.7,27);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(1,44);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(89,65);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(80.37,68);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(100,98);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
insert into WRAPPER_NUMERIC(VALUE,IDENTIFICATION_ID) values(12,173);
insert into WRAPPER_NUMERIC_PARENT(PARENT_ID, WRAPPER_NUMERIC_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_NUMERIC_SEQ.currval FROM DUAL;
-- заполним несколько денежных параметров и прицепим их к product_item
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (491.2,'RUR',22);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.03,'RUR',24);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (76.48,'RUR',25);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.88,'RUR',28);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.87,'RUR',29);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0,'RUR',30);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (9600,'RUR',37);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (15000,'RUR',42);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.44,'RUR',45);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.51,'RUR',46);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.6,'RUR',47);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.6,'RUR',48);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0.6,'RUR',49);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (1351,'RUR',56);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (2749.48,'RUR',57);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (626.26,'RUR',58);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0,'RUR',62);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (9600,'RUR',63);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (26500,'RUR',64);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0,'RUR',66);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (15000,'RUR',67);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (2100,'RUR',86);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (0,'RUR',89);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
insert into WRAPPER_MONEY(AMOUNT,CURRENCY,IDENTIFICATION_ID) values (1500,'RUR',90);
insert into WRAPPER_MONEY_PARENT(PARENT_ID, WRAPPER_MONEY_ID) SELECT PRODUCT_ITEM_SEQ.currval, WRAPPER_MONEY_SEQ.currval FROM DUAL;
commit;